# Python Imports

# Third-Party Imports

# Project Imports
from frag_pele.frag.PeleParameters.pele_parameter_paths import PeleParameterPaths


class PeleParameters:

    def __init__(self, pele_params_path: PeleParameterPaths, control_file: str, resfold: str, report: str, traject: str,
                 cpus: int, steps: int, pele_eq_steps: int, min_overlap: float, max_overlap: float, temperature: int,
                 seed: int, steering: int, translation_high: float,
                 rotation_high: float, translation_low: float, rotation_low: float, radius_box: float):
        """
        :param pele_dir: Absolute path to PELE executables.
        :param pele_license: Absolute path to PELE's license file.
        :param control_file: Name of the PELE's control file templatized.
        :param resfold: Name of the results folder.
        :param report: Prefix name of PELE's output file.
        :param traject: Prefix name of the trajectory file generated by PELE.
        :param cpus: Number of CPUs that will be used to perform the simulation.
        :param pele_eq_steps: Number of PELE steps that we want to perform in the equilibration.
        :param min_overlap: Minimun value of overlapping factor that will be replaced in the control file.
        :param max_overlap: Maximum value of overlapping factor that will be replaced in the control file.
        :param steps: PELE steps to do in each GS.
        :param temperature: Temperature to add in the control file.
        :param seed: Seed in the PELE's control file.
        :param steering: Steering parameter of the PELE's control file.
        :param translation_high: Translation (high value) of the PELE's control file. In anstrongs.
        :param translation_low: Translation (low value) of the PELE's control file. In anstrongs.
        :param rotation_high: Rotation (high value) of PELE's control file. In rad.
        :param rotation_low: Rotation (low value) of PELE's control file. In rad.
        :param radius_box: Radius box size of PELE's control file. In anstrongs.
        :param data: Path to PELE Data folder.
        :param documents: Path to PELE Documents folder.
        """
        pass


