#!/bin/bash
#SBATCH --job-name=test
#SBATCH --output=mpi_%j.out
#SBATCH --error=mpi_%j.err
#SBATCH --ntasks=48
#SBATCH --time=00-2:00:00
#SBATCH --qos=debug

module purge
unset PYTHONPATH
export PELE="/gpfs/projects/bsc72/PELE++/mniv/V1.6/"
export SCHRODINGER="/gpfs/projects/bsc72/SCHRODINGER_ACADEMIC"
export PATH=/home/bsc72/bsc72292/.conda/envs/frag_2_3_0/bin:$PATH
export PYTHONPATH="/gpfs/projects/bsc72/FragPELE/FragPELE2.3.4_testing/frag_pele:/gpfs/projects/bsc72/LibPrep/v1.1.1/lib_prep"

module load intel mkl impi gcc # 2> /dev/null
module load impi
module load boost/1.64.0

python -m pytest test_all.py -vv
