#!/bin/bash
#SBATCH --job-name=test
#SBATCH --output=mpi_%j.out
#SBATCH --error=mpi_%j.err
#SBATCH --ntasks=4
#SBATCH --time=00-2:00:00
#SBATCH --qos=debug

module purge
unset PYTHONPATH
export SCHRODINGER="/gpfs/projects/bsc72/SCHRODINGER_ACADEMIC"
export PATH=/gpfs/projects/bsc72/conda_envs/FragPELE/v3.0.0/bin:$PATH
export PYTHONPATH="/gpfs/projects/bsc72/FragPELE/v3.1.0-beta/frag_pele"

module load intel mkl impi gcc # 2> /dev/null
module load impi
module load boost/1.64.0

python -m pytest test_all.py -vv
