#!/bin/bash
/home/ryoji/software/Emma-1.3.1/bin/mm_pcca \
-inputtransitionmatrix ./matrix/transitionmatrixOf_Traj1_Traj2.dat \
-nclusters 7 \
-ofuzzy ./pcca/fuzzy.ms \
-ocrisp ./pcca/crisp.ms \
-osets ./pcca/sets.dat
