#!/bin/bash
/home/ryoji/software/Emma-1.3.1/bin/mm_timescales \
-i ./discretized/traj_* \
-sampling slidingwindow \
-reversible \
-timestep 1 \
-lagtimes 1 10 15 20 25 30 40 50 60 70 80 90 100 125 150 175 200 225 250 275 300 325 350 375 400 \
-neig 5 \
-o ./its/result.its
#-i ./discretized/MD_1.disctraj ./discretized/MD_2.disctraj ./discretized/MD_3.disctraj ./discretized/MD_4.disctraj ./discretized/MD_5.disctraj ./discretized/MD_6.disctraj ./discretized/MD_7.disctraj \
