#!/bin/bash

#SBATCH --qos=debug

#SBATCH --job-name=test

#SBATCH --output=mpi_%j.out

#SBATCH --error=mpi_%j.err

#SBATCH --ntasks=48

#SBATCH --time=00-2:00:00

module load python/3.6.1
export PYTHONPATH=/gpfs/projects/bsc72/lib/python3/:/gpfs/projects/bsc72/Ligand_growing_MN/AdaptivePELE_repo:$PYTHONPATH
python ../../grow_for_pele.py -cp 1w7h_preparation_structure_2w.pdb -x 5 -sef serie_file.conf --pele_eq_steps 6 --cpus 48 --steps 1 --temperature 1000
