#!/bin/bash
scriptabspath=$(cd ${0%/*} && echo $PWD/${0##*/})
BASEDIR="`dirname ${scriptabspath}`/.."

echo $BASEDIR

# read config
source ${BASEDIR}/bin/config

java ${jvmoptions} ${lib_classpath} sherlock.emma.cmd.CreateObservationFromClusterCentersCmd \
-iclusterCenters ./discretized/clusterCenters.dat \
-oObs1 ./observe/obs1.ascii \
-oObs2 ./observe/obs2.ascii
