#!/bin/bash
/home/ryoji/software/Emma-1.3.1/bin/mm_tpt \
-inputtransitionmatrix ./matrix/transitionmatrixOf_Traj1_Traj2.dat \
-seta ./tpt/setC.dat \
-setb ./tpt/setB.dat \
-oforwardcommittor ./tpt/forwardcommitor.dat \
-obackwardcommittor ./tpt/backwardcommitor.dat \
-oflux ./tpt/flux.dat \
-onetflux ./tpt/netflux.dat \
-coarsesets ./pcca/sets.dat \
-ocoarseforwardcommittor ./tpt/coarseforwardcommitor.dat \
-ocoarsebackwardcommittor ./tpt/coarsebackwardcommitor.dat \
-ocoarseflux ./tpt/coarseflux.dat \
-ocoarsenetflux ./tpt/coarsenetflux.dat
