# Python Imports

# Third-Party Imports

# Project Imports


class PeleParameterArchives:

    def __init__(self, control_file: str, resfold: str, report: str, traject: str):
        """
        :param control_file: Name of the PELE's control file templatized.
        :param resfold: Name of the results folder.
        :param report: Prefix name of PELE's output file.
        :param traject: Prefix name of the trajectory file generated by PELE.
        """
        self._control_file = control_file
        self._resfold = resfold
        self._report = report
        self._traject = traject

    # Properties
    @property
    def control_file(self):
        return self._control_file

    @property
    def resfold(self):
        return self._resfold

    @property
    def report(self):
        return self._report

    @property
    def traject(self):
        return self._traject
