#!/bin/bash
/home/ryoji/software/Emma-1.3.1/bin/mm_transitionmatrixAnalysis \
-inputtransitionmatrix ./matrix/transitionmatrixOf_Traj1_Traj2.dat \
-nev 5 \
-stationarydistribution ./matrix/stationarydistribution.dat \
-eigenvalues ./matrix/eigenvalues.dat \
-lefteigenvectors ./matrix/lefteigenvectors.dat \
-righteigenvectors ./matrix/righteigenvectors.dat
