#!/bin/bash
/home/ryoji/software/Emma-1.3.1/bin/mm_connectivity \
-i ./discretized/traj_* \
-o 
#-i ./discretized/MD_1.disctraj ./discretized/MD_2.disctraj ./discretized/MD_3.disctraj ./discretized/MD_4.disctraj ./discretized/MD_5.disctraj ./discretized/MD_6.disctraj ./discretized/MD_7.disctraj \
