#!/bin/bash
echo "Example command executes \""
echo "../bin/mm_assign"
echo "  -i ./modeltrajectories/traj1.traj ./modeltrajectories/traj2.traj"
echo "  -ic ./modeltrajectories/clusterCenters.dat"
echo "  -metric euclidean"
echo "  -o ./discretized"
echo "  - timecolumn"
echo ""
/home/ryoji/software/Emma-1.3.1/bin/mm_assign \
-i ./traj_*.dat \
-ic ./discretized/clusterCenters.dat \
-metric euclidean \
-timecolumn \
-o ./discretized
#-i ./MD_1.dat ./MD_2.dat ./MD_3.dat ./MD_4.dat ./MD_5.dat ./MD_6.dat ./MD_7.dat \
